postcss/postcss-calc

- index.js
- package.json
Fix #11
`postcss.plugin()` is very important, because I got today two reports that `postcss-calc` doesn’t work, because developers just miss brackets.
> Use PostCSS 4.1 API

- index.js
- package.json
@MoOx this PR is important for me, because I can’t run PostCSS benchmark until `postcss-calc` prints warnings.
> Use PostCSS 5.0 API (version 2)

- CHANGELOG.md
- README.md
- index.js
- test/fixtures/warnWhenCannotResolve.css
- test/fixtures/warnWhenCannotResolve.expected.css
- test/index.js
> Add throwWhenCannotReduce option

- CHANGELOG.md
- README.md
- index.js
- test/fixtures/calc.css
- test/fixtures/calc.expected.css
- test/fixtures/media.css
- test/fixtures/media.expected.css
- test/fixtures/preserve-media.css
- test/fixtures/preserve-media.expected.css
- test/index.js
> Add support for media queries

- README.md
- index.js
- test/fixtures/multiline.css
- test/fixtures/multiline.expected.css
- test/index.js
For those who like to write `calc()` on multilines or use a `max-line-length` rules in their CSS linter.
I wrote some tests for this.
@MoOx can you have a look ? I'm not realy sure if I've done it right.
*multiline.css*
```css
multiline {
font-size: calc(
1rem
* 2
* 1.5
);
width: calc(1px +
10px
+ 100px );
height: calc(
2em
+ 20em + 200em);
padding: calc(30px
+ 3px ) calc(
2px *
2
+40 px
);
}
```
*multiline.expected.css*
```css
multiline {
font-size: 3rem;
width: 111px;
height: 222em;
padding: 33px 44px;
}
```
- close #26
> Add support for multiline value

- src/__tests__/index.js
- src/lib/stringifier.js
- src/lib/transform.js
Original issue https://github.com/cssnano/cssnano/issues/725
> fix: do not break `calc` with single var

- package.json
- src/__tests__/index.js
- src/lib/reducer.js
> fix: properly handle nested add and sub expression inside sub expression

- src/__tests__/index.js
- src/lib/reducer.js
This PR should fix #88, where a division expression subtracted from zero is incorrectly reduced. Apparently `reducer.js` does not reduce division expressions if the denominator cannot be reduced to a value, so similar multiplication tests pass while division did not.
> fix: incorrect reduction of subtraction from zero (#88)

- src/__tests__/index.js
- src/lib/reducer.js
- src/lib/transform.js
Fix: https://github.com/postcss/postcss-calc/issues/110
> fix: substracted css-variable from zero

- src/__tests__/index.js
- src/lib/reducer.js
Closes https://github.com/postcss/postcss-calc/issues/107
1. Only remove the `something` in `(expr + something) +- (expr - something)` if it's actually addition and subtraction that cancel out.
2. Pull out common factors in `(expr * something) +- (expr * something)` (for `var` expressions https://github.com/postcss/postcss-calc/issues/107#issuecomment-680747619 )
> Correctly handle summands that cancel out and pull out common factors

- src/__tests__/index.js
- src/lib/reducer.js
fix https://github.com/postcss/postcss-calc/issues/120 fix https://github.com/postcss/postcss-calc/issues/122
The basic idea:
1. For serial addition expression like `1px + (2em + (3vh + 4px))`, we **collect all the addition items at once**, and merge those item with same "type". So that we can add the `1px` and `4px`.
2. If there is addition item that is a "multiplication/division expression", we try to turn it into addition expression. For example, for `1px - (2em + 4px - 6vh) / 2`, we unwrap the division and get `1px - 1em - 2px + 3vh`. Then the `1px - 2px` is done and become the final result: `-1px - 1em + 3vh`
It is worth noting that this refactor will somehow "revert" the work of https://github.com/postcss/postcss-calc/commit/9807c5ef07db4f619074cd6a4013221b60f5efd1  . 9807c5e try to …
> refactor reducer

- src/__tests__/index.js
- src/lib/transform.js
- yarn.lock
/cc @ludofischer @Semigradsky 
The main idea is avoid fatal error when we can't parse and keep value as it, should we use warning or error? Should we have options to change warning on error and versa vice.
> feat: avoid fatal error

- src/__tests__/index.js
- src/lib/reducer.js
- src/lib/stringifier.js
- src/parser.d.ts
- src/parser.jison
- types/lib/reducer.d.ts
Modify the parser to track parenthesized expressions.
Keep the parentheses if a function is inside.
Fix #113
Fix #115
I think the top comment in #115 was already working in 8.2; I've added a test to make sure.
> fix: preserve brackets around functions

- src/__tests__/index.js
- src/lib/reducer.js
fix: respect CSS var when reducing
Fix https://github.com/cssnano/cssnano/issues/1235
Preserve the parentheses around a math expression that contains a `var()` function call, to guarantee that the expression value stays the same.
The CSS custom properties might contain an addition or subtraction, so even distributing multiplication or division is not safe.
> fix: repect CSS var when reducing

- .babelrc
- .gitignore
- package.json
- pnpm-lock.yaml
- src/__tests__/convertUnit.js
- src/__tests__/index.js
- src/index.js
- src/lib/convertUnit.js
- src/lib/reducer.js
- src/lib/stringifier.js
- src/lib/transform.js
- tsconfig.json
- types/index.d.ts
- types/lib/convertUnit.d.ts
- types/lib/reducer.d.ts
- types/lib/stringifier.d.ts
- types/lib/transform.d.ts
Allow us to work on the code as it's really going to run
instead of the hybrid ConnonJS-ESM format that cannot run anywhere
natively.
`babel-plugin-add-module-exports` always overwrote module.exports,
so the module.exports.default that Babel created was not
visible to consumers.
I've tested importing the code from CommonJS and native ESM.
> chore: convert source to CommonJs and publish source directly

- package.json
- pnpm-lock.yaml
I think there might be an issue with the latest PostCSS 4.6 which causes some comments not to be removed any more, so it's better to investigate that separately. Two tests fail with PostCSS 8.4.6
> chore: update all deps except PostCSS

- CHANGELOG.md
- package.json
I think it's better to do one publish with the untranspiled source to check everything is OK with consumers, before we make any further changes. Especially concerning https://github.com/postcss/postcss-calc/pull/171, it might be better to not add comment processing to postcss-calc, since we already have that in postcss-discard-comments.
> chore(release): 8.2.4

- package.json
- test/convertUnit.js
- test/index.js
Bring the number of published files back to the previous level.
I considered using an .npmignore file but I think this solution
requires less npm knowledge to understand.
I've also renamed `__tests__` to `test` so the layout matches the
one in the postcss and webpack repositories.
> chore: move test directory ouf of src

- CHANGELOG.md
- package.json
Officially drop support for Node.js before 14
> Release postcss-calc 9.0

- src/lib/stringifier.js
- test/index.js
Fixes #181
This fix allows `calc` to be printed when `calc((...))` is encountered. The bug occurred because the AST was `'type: 'ParenthesizedExpression'` which didn't satisfy the [`shouldPrintCalc`](https://github.com/postcss/postcss-calc/blob/master/src/lib/stringifier.js#L75) check in `stringifier.js`. The test I added piggy backs on the work started in #180. All the original tests pass with this addition, but I am new to the codebase so I very well could be missing some things.
https://github.com/cssnano/cssnano/issues/1490#issuecomment-1534215112
TODOs:
- remove the extra parentheses e.g. `calc((var(--foo) / var(--bar))` should become `calc(var(--foo) / var(--bar)`
- preserve the space between the division operator e.g. `calc((var(--foo) / var(--bar))` should preserve the space if …
> fix: preserve calc when extra parentheses are used

- .github/workflows/test.yml
Bump action major version to prepare for Node.js 16 removal in GitHub actions
> chore: update GitHub actions

- parser.jison
- src/lib/reducer.js
- src/parser.d.ts
- test/index.js
> fix: add support for cqw unit
