- README.md
- index.js
- test/fixtures/selector.css
- test/fixtures/selector.expected.css
- test/index.js
Hi,
I implemented a new usefull feature for projects working with data attributes within css selectors.
Martin
> Added support for selector transformation

- package.json
Hi @postcss
Here comes another little update :)
> feat: update to postcss ^7.0.2

- src/lib/transform.js
`reduce` only accepts 2 parameters:
https://github.com/postcss/postcss-calc/blob/acecba21b4df978527ed5ddaff96d108472f52a4/src/lib/reducer.js#L3
> Remove third parameter

- src/__tests__/index.js
- src/lib/transform.js
> fix: better handle precision for nested calc

- src/__tests__/index.js
- src/parser.jison
> style: avoid tabs

- src/__tests__/index.js
> test: whitespace

- src/__tests__/index.js
> test: comments

- src/__tests__/index.js
- src/lib/transform.js
- src/parser.jison
fixes #76
Also it is give possible don't throws error on future css units, we just print their as is
> feat: relax parser on unknown units

- src/lib/reducer.js
- src/lib/stringifier.js
- src/parser.jison
According css unit spec let's use better name for nodes
> refactor: parser

- .babelrc
- package.json
- pnpm-lock.yaml
The source contains no unsupported features except modules.
> chore: simplify Babel transform

- src/lib/reducer.js
> chore: fix typo in function name

- package.json
- pnpm-lock.yaml
- src/__tests__/convertUnit.js
- src/__tests__/index.js
It's confusing to have more than 2 different test frameworks in postcss projects and the new ava release does not run on Node.js 10.
> test: migrate tests to uvu

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Adapted from the cssnano templates
> chore: add issue templates

- package.json
- pnpm-lock.yaml
- src/__tests__/index.js
Move the `test` call at the top level so that we can use `test.only`.  This lets us run a single test at a time.
> test: allow executing a single test

- README.md
Fix #106
* Show the effect of PostCSS Calc alone, so people don't expect it to resolve
custom properties.
* Remove outdated Travis badge
> docs: improve Readme

- .github/workflows/test.yml
* disable permissions
* raise actions versions
* raise pnpm version
> chore: update CI configuration

- package.json
> chore: update repository link

- package.json
> Remove duplicate repository field in package.json

- .github/workflows/test.yml
- .npmrc
- package.json
- pnpm-lock.yaml
Ensure compatibility with pnpm 8.6
> chore: update CI and dev dependencies

- parser.jison
- src/lib/reducer.js
- src/parser.d.ts
- test/index.js
This PR adds support for `lh` & `rlh` unit as requested in Issue #221.
> feat: add support for lh & rlh units

- parser.jison
- src/lib/reducer.js
- src/lib/stringifier.js
- src/parser.d.ts
- test/index.js
> fix: handle calc keywords correctly
